# Generated by Django 3.2.3 on 2021-05-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewee_email', models.CharField(max_length=100)),
                ('reviewer_email', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
    ]
